"""empty message

Revision ID: 03fe147135cc
Revises: 3532e907a9c3
Create Date: 2022-07-19 23:30:01.299527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03fe147135cc'
down_revision = '3532e907a9c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=80), nullable=False))
    op.create_unique_constraint(None, 'user', ['first_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
