"""empty message

Revision ID: 49d07c580647
Revises: 475e1a351197
Create Date: 2022-07-23 19:33:22.432578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49d07c580647'
down_revision = '475e1a351197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('username', sa.Integer(), nullable=True))
    op.drop_column('favorites', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('favorites', 'username')
    # ### end Alembic commands ###
