"""empty message

Revision ID: aa9e7eaa75bc
Revises: 8c8ef320885d
Create Date: 2022-07-21 02:28:02.880683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa9e7eaa75bc'
down_revision = '8c8ef320885d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('person_id', table_name='favorites')
    op.drop_index('person_id_2', table_name='favorites')
    op.drop_index('planet_id', table_name='favorites')
    op.drop_index('planet_id_2', table_name='favorites')
    op.add_column('user', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'favorites', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'user_id')
    op.create_index('planet_id_2', 'favorites', ['planet_id'], unique=False)
    op.create_index('planet_id', 'favorites', ['planet_id'], unique=False)
    op.create_index('person_id_2', 'favorites', ['person_id'], unique=False)
    op.create_index('person_id', 'favorites', ['person_id'], unique=False)
    # ### end Alembic commands ###
